// Created by Leopold Lemmermann on 02.06.23.

let examples: [Fact] = [
  Fact(content: "Each day, about 1,600 youth try their first cigarette", expiry: .distantFuture, language: .english),
  Fact(content: "Cigarette smoking kills more than 480,000 Americans each year.", expiry: .distantFuture, language: .english),
  Fact(content: "Arsenic, lead, tar — these are just few of more than 7,000 chemicals in tobacco smoke.", expiry: .distantFuture, language: .english),
  Fact(content: "Smoking kills over 6 million people worldwide every year.", expiry: .distantFuture, language: .english),
  Fact(content: "Fires that can be attributed to smoking kill 620 people in the U.S. every year.", expiry: .distantFuture, language: .english),
  Fact(content: "Every 6 seconds a person dies from a tobacco-related disease.", expiry: .distantFuture, language: .english),
  Fact(content: "353 people die of smoking-related lung cancer every day in the United State.", expiry: .distantFuture, language: .english),
  Fact(content: "If current trends continue, tobacco will claim 1 billion lives worldwide in the 21st century.", expiry: .distantFuture, language: .english),
  Fact(content: "Smokers have a 2–4 times higher chance of suffering from heart disease or having a stroke than non-smokers.", expiry: .distantFuture, language: .english),
  Fact(content: "Both men and women have a 25 times higher chance of developing lung cancer as a result of smoking.", expiry: .distantFuture, language: .english),
  Fact(content: "Smoking leads to gum disease and can contribute to tooth loss.", expiry: .distantFuture, language: .english),
  Fact(content: "It is estimated that over 4.5 trillion cigarette butts end up filling our landfills every single year.", expiry: .distantFuture, language: .english),
  Fact(content: "$26 million is spent every single day on tobacco advertising.", expiry: .distantFuture, language: .english),
  Fact(content: "Jeden Tag probieren etwa 1.600 Jugendliche ihre erste Zigarette aus.", expiry: .distantFuture, language: .german),
  Fact(content: "Zigarettenrauchen tötet jedes Jahr mehr als 480.000 Amerikaner.", expiry: .distantFuture, language: .german),
  Fact(content: "Arsen, Blei, Teer - das sind nur einige von mehr als 7.000 Chemikalien im Tabakrauch.", expiry: .distantFuture, language: .german),
  Fact(content: "Das Rauchen tötet jedes Jahr weltweit über 6 Millionen Menschen.", expiry: .distantFuture, language: .german),
  Fact(content: "Bei Bränden, die auf das Rauchen zurückzuführen sind, sterben in den USA jedes Jahr 620 Menschen.", expiry: .distantFuture, language: .german),
  Fact(content: "Alle 6 Sekunden stirbt ein Mensch an einer tabakbedingten Krankheit.", expiry: .distantFuture, language: .german),
  Fact(content: "Jeden Tag sterben in den Vereinigten Staaten 353 Menschen an Lungenkrebs, der auf das Rauchen zurückzuführen ist.", expiry: .distantFuture, language: .german),
  Fact(content: "Wenn sich derzeitige Trends fortsetzen, wird Tabak im 21. Jahrhundert weltweit 1 Milliarde Menschenleben fordern.", expiry: .distantFuture, language: .german),
  Fact(content: "Raucher haben ein 2-4 mal höheres Risiko, Herzkrankheiten oder Schlaganfälle zu erleiden als Nichtraucher.", expiry: .distantFuture, language: .german),
  Fact(content: "Sowohl Männer als auch Frauen haben ein 25-mal höheres Risiko, an Lungenkrebs zu erkranken, wenn sie rauchen.", expiry: .distantFuture, language: .german),
  Fact(content: "Rauchen führt zu Zahnfleischerkrankungen und kann zum Zahnverlust beitragen.", expiry: .distantFuture, language: .german),
  Fact(content: "Schätzungen zufolge landen jedes Jahr über 4,5 Billionen Zigarettenstummel auf unseren Mülldeponien.", expiry: .distantFuture, language: .german),
  Fact(content: "26 Millionen Dollar werden jeden Tag für Tabakwerbung ausgegeben.", expiry: .distantFuture, language: .german)
]
